### ISSUE TITLE
sphinx-autobuild html gives error ModuleNotFoundError: No module named 'sphinx_rtd_theme'

### ISSUE THREAD

**Issue by tomachinz** [nextcloud/documentation#5011]
I feel like I'm in the wrong directory.

Issue: `ModuleNotFoundError: No module named 'sphinx_rtd_theme'`

Still there after running `brew install sphinx-doc`

python --version
Python 3.8.5

I've never run SPHINXBUILD so, am a noob.

Later, I see it is running at port 8000 shaweet. But I only see `404: Not Found` due likely to my cd. But if I go into user_manual still:
```
user_manual git:(master) ✗ make SPHINXBUILD=sphinx-autobuild html
../build/change_file_extension.sh
make versions-template-all html-all merge-folders
sed -i '/Here goes the Langs/i <dd><a href="/server/latest/user_manual/br/">br</a></dd>' ./_templates/versions.html
sed: 1: "./_templates/versions.html": invalid command code .
make[1]: *** [add-lang-to-versions-template-br] Error 1
make: *** [html] Error 2
```
when make html I get
```
../build/change_file_extension.sh
make versions-template-all html-all merge-folders
sed -i '/Here goes the Langs/i <dd><a href="/server/latest/user_manual/br/">br</a></dd>' ./_templates/versions.html
sed: 1: "./_templates/versions.html": invalid command code .
make[1]: *** [add-lang-to-versions-template-br] Error 1
make: *** [html] Error 2
```

When in root, 
make SPHINXBUILD=sphinx-autobuild html
gives
```
rm -rf admin_manual/_build/html/com
cd admin_manual && make html
sphinx-autobuild -b html -D html_theme='sphinx_rtd_theme' -d _build/doctrees   . _build/html/com
+--------------------------------- manual build ---------------------------------
| Running Sphinx v3.2.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/local/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "/Users/tom/Github/nextcloud-documentation/admin_manual/conf.py", line 18, in <module>
    from conf import *
  File "/Users/tom/Github/nextcloud-documentation/conf.py", line 5, in <module>
    import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'

+--------------------------------------------------------------------------------
[I 200921 05:29:18 server:335] Serving on http://127.0.0.1:8000
[I 200921 05:29:18 handlers:62] Start watching changes
[I 200921 05:29:18 handlers:64] Start detecting changes

```

Initially I think I was trying the wrong dir:
```
(nextcloud-documentation) ➜  user_manual git:(master) ✗ pwd
/Users/tom/Github/nextcloud-documentation/user_manual
(nextcloud-documentation) ➜  user_manual git:(master) ✗ make SPHINXBUILD=sphinx-autobuild html
../build/change_file_extension.sh
make versions-template-all html-all merge-folders
sed -i '/Here goes the Langs/i <dd><a href="/server/latest/user_manual/br/">br</a></dd>' ./_templates/versions.html
sed: 1: "./_templates/versions.html": invalid command code .
make[1]: *** [add-lang-to-versions-template-br] Error 1
make: *** [html] Error 2
(nextcloud-documentation) ➜  user_manual git:(master) ✗
```

Again apologies as this is a very fresh install and I maybe need to do pip requirements.txt

**Comment by MorrisJobke** [comment]
> Again apologies as this is a very fresh install and I maybe need to do pip requirements.txt

Don't worry, but indeed this is listed in the requirements:

https://github.com/nextcloud/documentation/blob/master/requirements.txt#L4

So yes `pip -r requirements.txt` should solve your issue.
